# https://docs.codecov.io/docs/common-recipe-list
# https://docs.codecov.io/docs/commit-status#patch-status

coverage:
  status:

    project:
      default:
        target: auto
        threshold: 2%

    patch:
      default:
        target: auto
        threshold: 2%
